21:
- 山手線
- やまのてせん
- 山の手線
- やまのて
- yamanote
- yamate
82:
- 東武東上線
- 東上線
- とうじょうせん
- とうじょう
- tojo
- tojosen
- tj
133:
- 丸ノ内線
- 丸の内
- 丸の内線
- marunouchi
- まるのうち
50:
- 埼京線
- さいきょうせん
- saikyo
38:
- 中央線
- chuou
- ちゅうおうせん
324:
- 大阪市営中央線
